---
# TODO: PHP 7.2 support will be removed soon. This is only being left in here as
# a convenience for legacy PHP 7.2 users.
- name: Enable remi repo for PHP 7.2.
  set_fact: php_enablerepo="remi,remi-php72"
  when: php_version == "7.2"

- name: Enable remi repo for PHP 7.3.
  set_fact: php_enablerepo="remi,remi-php73"
  when: php_version == "7.3"

- name: Enable remi repo for PHP 7.4.
  set_fact: php_enablerepo="remi,remi-php74"
  when: php_version == "7.4"

- name: Enable remi repo for PHP 8.0.
  set_fact: php_enablerepo="remi,remi-php80"
  when: php_version == "8.0"

- name: Enable remi repo for PHP 8.1.
  set_fact: php_enablerepo="remi,remi-php81"
  when: php_version == "8.1"

- name: Enable remi repo for PHP 8.2.
  set_fact: php_enablerepo="remi,remi-php82"
  when: php_version == "8.2"

- name: Enable remi repo for PHP 8.3.
  set_fact: php_enablerepo="remi,remi-php83"
  when: php_version == "8.3"

- name: https://github.com/ansible/ansible/issues/64852
  when: ansible_distribution_major_version | int >= 8
  block:
    - name: Ensure dnf-plugins are installed on CentOS 8+.
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Enable DNF module for CentOS 8+.
      ansible.builtin.dnf:
        name: "@php:remi-{{ php_version }}"
        state: present

- name: Ensure the crb repository is enabled on CentOS 9+.
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  when: ansible_distribution_major_version | int >= 9
